version: "3"
services:
  redis:
    image: redis:6.2
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  rest:
    image: rest:1.0.2
    container_name: rest
    restart: unless-stopped
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    command: yarn run start:prod
  db:
    image: mariadb:10.6
    container_name: db
    environment:
      - MYSQL_USER=workshop
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=workshop
    ports:
      - 3306:3306
    command: ['mysqld']
